---
volumes:
  nextcloud-data:
  nextcloud-db:
services:
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - 80:80
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=ncpw
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_USER=ncuser
      - MYSQL_HOST=nextcloud-db
    restart: unless-stopped
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=ncpw
      - MYSQL_DATABASE=nextclouddb
      - MYSQL_USER=ncuser
    restart: unless-stopped